# Generated by Django 2.0.3 on 2018-12-03 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_Comment', models.CharField(max_length=140)),
                ('time', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='freetipsgame',
            options={'ordering': ['-ticket__date_added']},
        ),
        migrations.AlterModelOptions(
            name='puntertipsgame',
            options={'ordering': ['-ticket__date_added']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='viptipsgame',
            options={'ordering': ['-ticket__date_added']},
        ),
        migrations.RemoveField(
            model_name='freetipsgame',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='puntertipsgame',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='viptipsgame',
            name='date_added',
        ),
    ]
